export {default as Vector} from './vector'
export {default as MapQuest} from './map-quest'
export {default as OSM} from './osm'
export {default as BingMaps} from './bingmaps'
export {default as ImageArcGISRest} from './image-arcgis-rest'
